### ISSUE TITLE
add-path is deprecated

### ISSUE THREAD

**Issue by enyo** [vanesyan/setup-dart#1]
The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

![image](https://user-images.githubusercontent.com/133277/96886891-50df9280-1484-11eb-8aaa-a5c71ede27a1.png)

**Comment by segfaultmedaddy** [comment]
Hello! Thanks for opening the issue. Seems like it is easy fix I need just to bump `@actions/core`.

**Comment by segfaultmedaddy** [comment]
Done, try out v1.

Feel free to reopen issue, if problem still persists for you.
